services:
  - type: web
    name: royalbank-sphinx
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn sphinx.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "rbc-bank.com,www.rbc-bank.com,royalbank-sphinx.onrender.com,*.onrender.com"
      - key: DATABASE_URL
        value: postgresql://royalbank_db_user:2ZQf105WxqmRC6M2jy6dP4wKI0dq69yB@dpg-d453omeuk2gs73fsdgfg-a.oregon-postgres.render.com/royalbank_db
      - key: DEFAULT_FROM_EMAIL
        value: "support@virement.net"
      # Configuration SMTP pour virement.net
      # Serveur sortant: mail.virement.netcopie ou mail16.lwspanel.com
      # Port SMTP: 587 (TLS) ou 465 (SSL)
      # Authentification requise: Oui
      - key: EMAIL_HOST
        value: "mail.virement.netcopie"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        value: "support@virement.net"
      - key: EMAIL_HOST_PASSWORD
        sync: false # Ã€ configurer manuellement dans Render Dashboard avec le mot de passe du compte email (utilisez un Secret)
      - key: EMAIL_USE_TLS
        value: "1"
      - key: EMAIL_USE_SSL
        value: "0"
      - key: SITE_URL
        value: "https://rbc-bank.com"

databases:
  - name: royalbank-db
    plan: free
    databaseName: royalbank
    user: royalbank_user
